### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by theuguest** [DIRKMJK/limepy#15]
Hi! I'm using `download.get_responses` and the connection to remote-control web if working perfectly, but for some sid's I have the error `'charmap' codec can't encode character '\U0001f449' in position 1064935: character maps to <undefined>` 
I tried to redefine the encoding using `sys.getdefaultencoding(), 'replace` but I'm thinking how can I add this line to the reading process before I could do the `path.write_text(csv)` 
This is happening with some of the surveys I had on my website, not all of them.
If you can help me with that or give me some ideas, I'll appreciate it a lot. Thank you.

**Comment by DIRKMJK** [comment]
Hi Daniella, thanks for your feedback! My first thought was that the problem was caused by an emoji (👉), but I tested it and had no problem exporting an answer containing this emoji. Can you think of any other ways in which the surveys that resulted in problems are different from the ones you didn’t have problems with?

**Comment by theuguest** [comment]
Thank you for your answer! I identified that my actual encoding didn't recognize the emojis, and I had problems reading the files. I did the same from another computer with another encoding treatment, and now I can run the code perfectly. It helped to know that was an emoji’s issue. For further surveys, I’m going to restrict that type of character just in case. Thanks again!

**Comment by DIRKMJK** [comment]
Glad to hear to managed to fix it!
